name: Publish to Docker Hub

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - run: |
          VERSION=${GITHUB_REF:11}
          docker login -u jayfong -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker buildx build --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x --push -t jayfong/caddy:latest -t jayfong/caddy:${VERSION} .
